#!/bin/sh
set -ve
if ! ./tinyboot.py hello42.tbf1 > hello42; then cat hello42; exit 1; fi
chmod 755 hello42
./hello42 || echo $?

./tinyboot.py Q.tbf1
if ! ./tinyboot.py tinyboot1.tbf1 < Q.tbf1 > Q; then cat Q; exit 1; fi
chmod 755 Q
strace ./Q

./tinyboot.py hi.tbf1
if ! ./tinyboot.py tinyboot1.tbf1 < hi.tbf1 > hi; then cat hi; exit 1; fi
chmod 755 hi
strace ./hi

echo x | ./tinyboot.py cat1.tbf1
if ! ./tinyboot.py tinyboot1.tbf1 < cat1.tbf1 > cat1; then cat cat1; exit 1; fi
chmod 755 cat1
echo x | strace ./cat1

if ! ./tinyboot.py cat.tbf1 < cat.tbf1 > tmp.out ; then cat tmp.out; exit 1; fi
cmp cat.tbf1 tmp.out
if ! ./tinyboot.py tinyboot1.tbf1 < cat.tbf1 > cat ; then cat cat; exit 1; fi
chmod 755 cat
./cat < cat.tbf1 > tmp.out
cmp cat.tbf1 tmp.out
./cat < tinyboot1.tbf1 > tmp.out # larger files sometimes show problems
cmp tinyboot1.tbf1 tmp.out
rm tmp.out

echo passamaquoddy | ./tinyboot.py star.tbf1
if ! ./tinyboot.py tinyboot1.tbf1 < star.tbf1 > star ; then cat star; exit 1; fi
chmod 755 star
echo passamaquoddy | strace ./star

if ! ./tinyboot.py tinyboot1.tbf1 < tinyboot1.tbf1 > tb1; then cat tb1; exit 1; fi
chmod 755 tb1
time ./tb1 < tinyboot1.tbf1 > tb2
cmp tb1 tb2
chmod 755 tb2

./trim.py -i < tinyboot1.tbf1 > trimmed.tbf1
time ./tb1 < trimmed.tbf1 > trimmed
cmp tb2 trimmed
wc trimmed.tbf1
